name: hare
base: core22
adopt-info: harec
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: classic

apps:
  qbe:
    command: usr/local/bin/qbe
  harec:
    command: usr/local/bin/harec
  hare:
    command: usr/local/bin/hare
    environment:
      PATH: $PATH:$SNAP/usr/local/bin
  haredoc:
    command: usr/local/bin/haredoc
  redis-cli:
    command: usr/local/bin/redis-cli

parts:
  qbe:
    plugin: make
    source: git://c9x.me/qbe.git
    build-attributes:
      - enable-patchelf
  harec:
    after: [qbe]
    plugin: autotools
    source: https://git.sr.ht/~sircmpwn/harec
    source-type: git
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --always --dirty --abbrev=10)
    build-packages: [scdoc]
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin/
    build-attributes:
      - enable-patchelf
  hare:
    after: [harec]
    plugin: make
    source: https://git.sr.ht/~sircmpwn/hare
    source-type: git
    override-pull: |
      craftctl default
      patch < ../../../config.patch
      cp config.example.mk config.mk
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin/

  # Extended libraries
  hare-compress:
    after: [hare]
    plugin: make
    source: https://git.sr.ht/~sircmpwn/hare-compress
    source-type: git
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin/
  hare-redis:
    after: [hare]
    plugin: make
    source: https://git.sr.ht/~sircmpwn/hare-redis
    source-type: git
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin/
    override-build: |
      craftctl default
      mkdir -p "$CRAFT_PART_INSTALL/usr/local/bin"
      cp redis-cli "$CRAFT_PART_INSTALL/usr/local/bin/"
  hare-json:
    after: [hare]
    plugin: make
    source: https://git.sr.ht/~sircmpwn/hare-json
    source-type: git
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin/
  hare-xml:
    after: [hare]
    plugin: make
    source: https://git.sr.ht/~sircmpwn/hare-xml
    source-type: git
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin/
  hare-png:
    after: [hare]
    plugin: make
    source: https://git.sr.ht/~sircmpwn/hare-png
    source-type: git
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin/
  hare-linux:
    after: [hare]
    plugin: make
    source: https://git.sr.ht/~sircmpwn/hare-linux
    source-type: git
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin/
